workers:
  pdfWorker:
    - name: id
      type: text
    - name: age
      type: number
  excelWorker:
    - name: implemented
      type: checkbox
  photoWorker:
    - name: firstName
      type: text
  specificWorker:
    - name: weight
      type: number
    - name: name
      type: text
    - name: isGood
      type: checkbox

