workers:
  xml:
    - name: id
      type: text
    - name: age
      type: number
  txt:
    - name: implemented
      type: checkbox
  json:
    - name: firstName
      type: text
  yml:
    - name: weight
      type: number
    - name: name
      type: text
    - name: isGood
      type: checkbox

