name: bob

workers:
  - xml:
      - name: id
        type: string
      - name: age
        type: int
  - txt:
      - name: implemented
        type: boolean
  - json:
      - name: firstName
        type: String

